### PR TITLE
Fix Search Feature

### PR DESCRIPTION
**Pull request by indigosquirrelio**
This fixes issue https://github.com/zuhao/isitfedoraruby/issues/10 and prettifies the search url.

### CODE REVIEW

**Comment by animesht** [comment]
Hey Mark,

Was it necessary to edit jQuery.tokeniput.js?

**Comment by indigosquirrelio** [comment]
I deleted the one line of jQuery.tokeninput.js because otherwise, the search box is cleared when you unfocus. I thought it would be better if the text persists.

**Comment by movitto** [comment]
Hey areke, like animesh said we can't edit jquery.tokeninput.js. It is a dependency which we pull in as is (modifying dependencies often have unintended consequences).

Animesh is working on making sure the search box isn't cleared so don't worry about that issue. Just focus on the problem at hand, eg preserving the search query in the url.

Thanks (I'll be available for the rest of today to help)

**Comment by movitto** [comment]
Pushed, thanks for the hard work!

**Pull request closed without merging**
